### PR TITLE
Change default value of Gallery.ServiceDiscoveryUri application key

### LINKED ISSUE #2615: ServiceDiscoveryUri value of "n" ?
In the latest web.config, there is a value of "n" for the ServiceDiscoveryUri application config key.  This entry also looks to be a dupe key.  It looks like it should be removed.

### PR DESCRIPTION
**Pull request by c0state**
Fixes #2615 - duplicate app key which causes application not to load up since it's not a URI

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
Where do you see the duplicate?

**Comment by maartenba** [comment]
Can you update the pull request to just remove the value of "n"? The key should be there but can be empty instead of "n" (it's not a duplicate for sure)

**Comment by c0state** [comment]
Ok, by dupe i meant that the comment had the example of how to set it and future users would create a new key by copying that and using it in the config.

But if the convention is to keep a null key, I'll amend the pull request.

**Comment by maartenba** [comment]
Thanks Stephen! That would be perfect.

**Comment by c0state** [comment]
OK, requested change was made--please take another look...

**Comment by maartenba** [comment]
Thanks, merged it into dev.

**Pull request closed without merging**
