### PR TITLE
Issues #2871 & #5839: Added ability to use AWS S3 as a backing store for the package files.

### PR DESCRIPTION
**Pull request by Texernie**
#2871

### CODE REVIEW

**Comment by Texernie** [comment]
I tried to follow the FileSystemFileStorageService and FileSystemService as close as I could. I also patterned some stuff after the existing CloudBlobFileStorageService when needed.

**Comment by Texernie** [comment]
#5839

**Comment by anangaur** [comment]
Thanks for your contribution to NuGet. The Gallery code base currently supports two storage backends: local files and Azure. Both are constantly used and tested by us: we deploy nuget.org on Azure, and our development environments use local files. NuGet Gallery doesn’t support additional infrastructures since we can’t reliably test and maintain those integrations. We do believe that users should be able to use the Gallery with any storage backend and suggest adding an extensibility point that will enable those scenarios. 

Gallery already has support for extensions (see [here](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/App_Start/DefaultDependenciesModule.cs#L677)). Currently it's used for Auditing extensions. This can be extended to support Storage extensions as well. The NuGet team will be more than willing to help you out by reviewing the design/code. We have created [an issue](https://github.com/NuGet/NuGetGallery/issues/5982) to track this extensibility approach.

**Comment by anangaur** [comment]
@Texernie as we are exploring extension based options at https://github.com/NuGet/NuGetGallery/issues/5982, I am closing this PR.

**Pull request closed without merging**
