### PR TITLE
Update ApiController.cs

### PR DESCRIPTION
**Pull request by starshayayord**
invoke reindexing after uploading package through api

### CODE REVIEW

**Comment by maartenba** [comment]
@starshayayord Will have a look at this over the next few days.

**Comment by yishaigalatzer** [comment]
What issue or bug I this resolving? What testing was performed to verify this change?

**Comment by starshayayord** [comment]
@yishaigalatzer 
if you upload package using api (nuget.exe push <pkg> -s <url> <ApiKey>),  it does not appear in the list in the Web application instantly. You can wait for the rebuild of the index. This change initiates the rebuilding of the index immediately after loading the package through the api.

**Comment by xavierdecoster** [comment]
Seems we already call `IndexingService.UpdatePackage(package)` ([in ApiController.PublishPackage](https://github.com/NuGet/NuGetGallery/blob/master/src/NuGetGallery/Controllers/ApiController.cs#L403)) for the following routes:
```
POST /v1/PublishedPackages/Publish
POST /api/v2/package/{id}/{version}
```

The following routes currently do not call into `IndexingService.UpdatePackage(package)`:
```
POST /v1/PackageFiles/{apiKey}/nupkg
PUT /api/v2/package
```

This PR fixes that.
At first glance, this seems like a good fix to me!

@johnataylor : any idea why we don't do this currently? Bug or by design?

**Comment by yishaigalatzer** [comment]
I'm not inclined to take changes in this area, until we get the eventual consistency issue right with proper tests surrounding every change.

**Comment by xavierdecoster** [comment]
Some additional background: this change only affects "private" galleries. NuGet.org uses an external index and is not affected by this change in any way, as its index is external to the gallery.

**Comment by yishaigalatzer** [comment]
Makes sense, then lets take it once we have test coverage

**Comment by yishaigalatzer** [comment]
@starshayayord @xavierdecoster do you think we need more testing here, or is this ready to go?

**Comment by xavierdecoster** [comment]
@starshayayord would be good to complete the PR with a unit test in `ApiControllerFacts.TheCreatePackageAction` that verifies whether `IndexingService.UpdatePackage` is called for the `CreatePackagePost` action on the `ApiController`.

You can take a look at `ApiControllerFacts.TheCreatePackageAction.WillCurateThePackage` for an example.

Once that's in, this is good to be merged and ready for test on our DEV and INT environments.

**Comment by starshayayord** [comment]
is this what u want? d5b93ca7bae225610fcfa5b99e15d7c94a1bef14

**Comment by yishaigalatzer** [comment]
@xavierdecoster can you please take a look at the new commit?

**Comment by xavierdecoster** [comment]
Looks good, thanks!

**Pull request merged**
