### PR TITLE
WIP: Remove semver2 warning

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by joelverhagen** [comment]
@SimonCropp, thanks for the contribution! What do you see as the remaining steps to remove the `WIP:` in the title? 

@skofman1 - can we just take this? I think @SimonCropp brought this up on Twitter some time ago. I ran some numbers at that time:
https://twitter.com/joelverhagen/status/1169679215127486464

@anangaur seemed on board:
https://twitter.com/adgrv/status/1169679507336224768

**Comment by SimonCropp** [comment]
@joelverhagen not finished yet. there is still some redundant code in the view model. is there any way to unlock the CI so i can ensure i dont break anything over multiple commits?

**Comment by SimonCropp** [comment]
> we don't have automatic CI enabled for external PRs

OK i will clean up the other things i think are required and get a review :) ETA 24 hours

**Comment by skofman1** [comment]
Long time overdue 😸 
Please open an issue to track the problem you are fixing. This is the team process.

**Comment by SimonCropp** [comment]
but a PR “is an issue”. just with files attached. all the process things you do with an issue you can also do with a PR

**Comment by SimonCropp** [comment]
ok i just read this https://github.com/NuGet/NuGetGallery/blob/master/CONTRIBUTING.md#getting-started

so i will close this

**Pull request closed without merging**
