### PR TITLE
Add comment that Enable-LocalTestMe.ps1 does not work on Windows <8

### PR DESCRIPTION
**Pull request by scottbommarito**
`Netsh` doesn't support SNI on versions of Windows before 8, so `Enable-LocalTestMe.ps1` will fail when run. Added a comment in the docs that this is the case.

Do we want to add a comment about alternatives to running `Enable-LocalTestMe.ps1` as well?

(Fixes https://github.com/NuGet/NuGetGallery/issues/3162)

### CODE REVIEW

**Comment by scottbommarito** [comment]
forgot to tag
@harikmenon @maartenba @skofman1

**Comment by maartenba** [comment]
Ship it (but to `dev` branch please :))

**Comment by skofman1** [comment]
:ship:

**Comment by scottbommarito** [comment]
reopening on dev

**Pull request closed without merging**
