### PR TITLE
fixes #2747

### LINKED ISSUE #2747: Optimize telemetry by using sampling
See also https://github.com/Azure/azure-content/blob/master/articles/application-insights/app-insights-sampling.md

### PR DESCRIPTION
**Pull request by xavierdecoster**
This PR fixes #2747:
* Upgrades Application Insights SDK to 2.0.0-beta2
* Adds support for telemetry sampling through new configuration setting `Gallery.AppInsightsSamplingPercentage`, which has default value of 100 (effectively disabling sampling by default)

cc @maartenba @joyhui @yishaigalatzer @johnataylor

### CODE REVIEW

**Comment by maartenba** [comment]
What is the sampling percentage we will configure? (also where is it configured?)

**Comment by xavierdecoster** [comment]
@maartenba See https://github.com/NuGet/NuGetGallery/commit/841e16a433d22c72ea2843f2e446ee0f5509cebc and comment [here](https://github.com/NuGet/NuGetGallery/pull/2780/files#diff-2247d34f9feacec1a6168afc5ca77336R61). Setting it to 50% for PROD should be good enough for now.

**Comment by maartenba** [comment]
:shipit:

**Comment by joyhui** [comment]
What 50% means? Why not use 100% always?

**Comment by xavierdecoster** [comment]
It means we reduce telemetry output by 50%. AppInsights SDK takes care of the sampling method to guarantee statistical correctness.

> For the sampling percentage, choose a percentage that is close to 100/N where N is an integer. Currently sampling doesn't support other values.

Source: https://github.com/Azure/azure-content/blob/master/articles/application-insights/app-insights-sampling.md

**Comment by xavierdecoster** [comment]
The issue being fixed with this PR is about avoiding telemetry throttling.

**Comment by joyhui** [comment]
:+1:

**Pull request merged**
