### PR TITLE
CES Experiment

### PR DESCRIPTION
**Pull request by harikmenon**
Adding a simple survey link to gauge Customer Effort Score. Starting small as a experiment to see if we can get folks to give us feedback. Will look into expanding more and redesigning if we are getting less responses.

### CODE REVIEW

**Comment by harikmenon** [comment]
untitled

This is how it looks like now.

@maartenba can you review?

**Comment by maartenba** [comment]
Looks good to me, although I wonder if it's "in your face" enough.

Adding @skofman1 for second pair of eyeballs.

**Comment by harikmenon** [comment]
Totally agreed, hence the experiment. I wanted to start of small see if there is an impact if not change it up a bit. Might have to use some custom styling since our default styles like message and info was a bit too much in your face for a survey link :)

**Comment by skofman1** [comment]
LGTM. If would add a link at the main page as well.

**Comment by harikmenon** [comment]
This is something I want to start with Authors at this point. Consumers we will add to VS Client to start with. 

That way I can have the score separate without adding a extra pivot in the survey.

**Comment by harikmenon** [comment]
Can i merge then?

**Comment by maartenba** [comment]
Aye

**Comment by harikmenon** [comment]
When will this get deployed :)?

**Pull request merged**
