### PR TITLE
Allow user selection in install command

### PR DESCRIPTION
**Pull request by JakubHaladej**
https://github.com/NuGet/NuGetGallery/issues/8886 Prevent autoselection in command box so user can select parts he wants.

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8892) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8892) before we can accept your contribution.<br/><br/>:x: JakubHaladej [sign now](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8892)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/NuGetGallery?pullRequest=8892) it.</sub>

**Comment by drewgillies** [comment]
Hi, @JakubHaladej --thanks so much for contributing, and we'll get to reviewing this when we can! Much appreciated.

**Comment by kolpav** [comment]
@drewgillies Hi, is there any progress on this? I keep hitting this problem daily hoping it would get fixed.

**Review by loic-sharma — APPROVED** [review]

**Comment by loic-sharma** [comment]
Thanks for the reminder @kolpav, we'll get this merged and deployed! :)

**Review by joelverhagen — APPROVED** [review]

**Review by lyndaidaii — APPROVED** [review]

**Comment by loic-sharma** [comment]
Thanks @JakubHaladej for your contribution! We'll work on deploying this to nuget.org. You can follow our progress using this work item: https://github.com/NuGet/NuGetGallery/issues/8886

**Pull request merged**
