### PR TITLE
added AllowHtml attribute to avoid errors in contact form submissions…

### PR DESCRIPTION
**Pull request by mgroves**
This is the exact fix suggested for issue #3448: I added the AllowHtml attribute to the SubjectLine and Message fields on the view model.

### CODE REVIEW

**Comment by robertmuehsig** [comment]
When I checked the code I noticed a few code parts that might need some work: 
- As far as I know the contact message must be Html.Encoded when sending the email (I'm not sure if this is already the case...)
- There is a /Admin area available, which also shows the contact requests and I'm not 100% sure if those messages are Html.Encoded as well - otherwise it would be a huge attack vector.

**Comment by scottbommarito** [comment]
We need to be 100% sure that this still HTML encodes the fields before saving (`<` becomes `&lt;`) or otherwise processing them. If it is not encoded before it is saved, as @robertmuehsig said, it will be sent as decoded and fully valid HTML to our support email address as well as the /Admin support request portal which is a massive security hole. I'm not quite sure the behavior of `[AllowHtml]` so it may encode the HTML but it also might not.

**Comment by mgroves** [comment]
I will check to see if AllowHtml does any encoding. If it does, then I don't see a need for unit tests. If it doesn't, then I will need to add that encoding somewhere, and that will need unit tests of course.

**Comment by robertmuehsig** [comment]
AllowHtml itself just let pass through all values even if it looks like Html. When this is inserted in a email, it must be Html.Encoded, otherwise the plain HTML will be injected into the mail body. 
In the MVC View it might be easier, because if you use @ViewModel.Foobar it will be Html.Encoded, but there are cases where you could do something like @Html.Raw(ViewModel.Foobar), which is not encoded.
See also this comment from a previous PR https://github.com/NuGet/NuGetGallery/pull/3388#pullrequestreview-12331456

**Comment by mgroves** [comment]
I made the assumption that encoding should be performed in the controller action.

**Pull request merged**
