### PR TITLE
Remove .vs folder with applicationhost.config from repo

### PR DESCRIPTION
**Pull request by robertmuehsig**
Currently it is already marked as ignored file, but it is currently tracked - so we need to remove it.

### CODE REVIEW

**Comment by scottbommarito** [comment]
I think we actually have it in the repo intentionally, but I forgot the particular reason why.

@skofman1 @xavierdecoster

**Comment by xavierdecoster** [comment]
If I remember correctly, the reason we have it is for the localtest.me bindings. It is ignored afterwards, to avoid changes because of people checking out the sources in a different place on disk.

**Comment by robertmuehsig** [comment]
Mh... mh... I noticed the localtest me stuff in applicationhost. I just noticed the file because everytime I open the NuGetGallery solution this file is marked as changed.

**Comment by scottbommarito** [comment]
Yeah it's pretty annoying to have to unmark `applicationhost.config` with every single commit. I'm not sure if there's a better solution.

**Comment by xavierdecoster** [comment]
Everytime you launch VS locally, it wants to replace relative paths with absolute paths and these often end up pushed to the remote.

However, there is a way to tell git to ignore changes to an already committed file, so it no longer appears in your pending changes or commits:

```
git update-index --assume-unchanged .vs/config/applicationhost.config
```

Source: http://git-scm.com/docs/git-update-index/

**Comment by robertmuehsig** [comment]
For the history books: 
The actual useful content of the applicationhost.config that makes it work with the localtest.me binding is this:

            <site name="NuGet Gallery (nuget.localtest.me)" id="2">
                <application path="/">
                    <virtualDirectory path="/" physicalPath="D:\Code\GitHub\NuGetGallery\src\NuGetGallery" />
                </application>
                <bindings>
                    <binding protocol="http" bindingInformation="*:80:nuget.localtest.me" />
                    <binding protocol="https" bindingInformation="*:443:nuget.localtest.me" />
                </bindings>
            </site>

Unfortunately vs is creating this monster xml and without this setting nothing works. 

The current solution is not ideal, but the only other way would be to enhance EnableLocalTestMe.ps1 to create the applicationhost.config with the correct binding - but this is also not very elegant.

Maybe the git update-index command could be added to the readme as number 8 in the "Build and Run the Gallery in (arbitrary number) easy steps"? 
(I would also vote to add the web.config to this --assume-unchanged - at least I often change the Gallery.ConfirmEmailAddresses" setting to false.)
Another enhancement would be to add a short comment in the gitignore file why this file is untracked, but the same time already committed.

What do you think?

**Comment by xavierdecoster** [comment]
I agree with you @robertmuehsig. Unless or until someone has a better idea, my vote is on adding this to the readme, as it is not a requirement although useful for convenience. Willing to send a PR for that? :)

Perhaps also add instructions on how to undo this `--assume-unchanged` action (using `--no-assume-unchanged`) for when someone does want to commit a change e.g. to the web.config file.

**Comment by robertmuehsig** [comment]
Sure - will create a new PR tomorrow - will close this one.

**Comment by xavierdecoster** [comment]
Thanks @robertmuehsig !

**Pull request closed without merging**
