### PR TITLE
Add a "Add new (upload)" link to the Manage Packages view breadcrumb navigation

### PR DESCRIPTION
**Pull request by xavierdecoster**
Addresses #5728 

image

### CODE REVIEW

**Comment by xavierdecoster** [comment]
I have the feeling there's more to it than just adding this link, but happy to make this PR incremental.

@anangaur Can you please provide what are the additional requirements for the below screenshot? 
e.g. noticing a dropdown to the right

image

**Comment by anangaur** [comment]
The drip down to the right is the owner filter that is not inline with the site theme today. The width of the filter drop down should be increased and the drop down button should be different than what is present today. We should use the same icon for dropdiwn as we use for expandable sections on NuGet.org

**Comment by agr** [comment]
Why do we need two links to the same upload page there?

**Comment by scottbommarito** [comment]
@anangaur I think `Upload new` without "add" would look a lot better.
Also, I think dropdown changes should be made in a separate PR--the issue that this PR is targeting is very specifically focused on upload links and not other UI.

**Comment by anangaur** [comment]
I would say just `+ Add new` is sufficient. It will anyway take you to the upload page.

**Comment by xavierdecoster** [comment]
Updated:

image

image

**Pull request merged**
