### PR TITLE
Remove alert.md, service alert api and introduce new banner config

### PR DESCRIPTION
**Pull request by robertmuehsig**
Should resolve this issue https://github.com/NuGet/NuGetGallery/issues/2973

### CODE REVIEW

**Comment by xavierdecoster** [comment]
Another great contrib! Thx @robertmuehsig!

Changes look good to me. 
What do you think @maartenba?

**Comment by maartenba** [comment]
Looks good! Would you mind rebasing this onto `dev`?

**Comment by robertmuehsig** [comment]
Git Noob Question - I did the following:
- git fetch upstream
From https://github.com/NuGet/NuGetGallery
   12e96a0..297f144  dev        -> upstream/dev
   9f1dbdf..297f144  master     -> upstream/master
- git checkout 2973-remove-alert.md
- git rebase upstream/dev
First, rewinding head to replay your work on top of it...
Applying: remove alert.md, status api and introduce new banner config
- git push -f origin 2973-remove-alert.md

And when I look at my 2973-branch I see all commits that are also on your dev-branch - so - correct, right?

**Comment by xavierdecoster** [comment]
Thanks! Looks good.
Merged with 1a515fd2c783f721d2d5552be83a4534dd70cb59

**Pull request closed without merging**
