### PR TITLE
Fix #1635 - Escape underscores in packages for markdown

### LINKED ISSUE #1635: Support request emails accidentally remove underscores from package links
We got an email today which I imagine should have linked to 

https://www.nuget.org/packages/JQueryFileUpload_Demo_with_Backload/

but it actually linked to 
http://www.nuget.org/packages/JQueryFileUploadDemowithBackload/
and
http://www.nuget.org/packages/JQueryFileUploadDemowith_Backload/1.9.2.4
which didn't work

### PR DESCRIPTION
**Pull request by robertmuehsig**
Should fix this issue https://github.com/NuGet/NuGetGallery/issues/1635

I tested it with this package https://www.nuget.org/packages/JQueryFileUpload_Demo_with_Backload/

Now he ReportPackageRequest creates such an MailBody with correct escapted underscore. Poor mans solution, but should work.

**Email:** admin (...)

**Package:** JQueryFileUpload_Demo_with_Backload
http://nuget.localtest.me/packages/JQueryFileUpload\_Demo\_with\_Backload/

**Version:** 1.9.2.4
http://nuget.localtest.me/packages/JQueryFileUpload\_Demo\_with\_Backload/1.9.2.4

**User:** admin (...)
http://nuget.localtest.me/profiles/admin

**Reason:**
The package was published as the wrong version

**Message:**
test

_Message sent from NuGet Gallery_

---

Only problem: The escaped PackageID is now also displayed in the mail subject - but I guess this is a very rare case and with this PR the link and the ID is correct in the mail body.

### CODE REVIEW

**Comment by robertmuehsig** [comment]
Is this pull request still interesting?

**Comment by yishaigalatzer** [comment]
@xavierdecoster can you please review?

**Comment by 304NotModified** [comment]
Bump!

**Comment by yishaigalatzer** [comment]
@qianjun22 this is an ancient PR, can we please figure out if we want it and merge ?

**Comment by skofman1** [comment]
Closing this PR since it's very old and has a lot of merge conflicts.

**Comment by robertmuehsig** [comment]
Is this something that is still a problem? I could create a new PR.

**Comment by skofman1** [comment]
This: https://github.com/NuGet/NuGetGallery/issues/1635 is still open, and I couldn't find any indication in the code that it was.. a new PR will be great.

**Pull request closed without merging**
