### PR TITLE
collapse the preview and vulnerable versions in the version tab

### LINKED ISSUE #10172: [Feature]: collapse the preview and deprecated versions in the version tab
### Related Problem

I’ve noticed that as [the package version list](https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection) gets longer, it’s becoming hard to find specific versions because there are so many different types mixed in, like preview versions, stable versions, and deprecated ones.  Can we consider folding the preview or deprecated versions and only show the stable ones expanded?

### The Elevator Pitch

collapse the preview and deprecated versions in the version tab

### Additional Context and Details

_No response_

### PR DESCRIPTION
**Pull request by Varorbc**
## Before
d0af605c6802e38506f0c824dcb1c968

## After
f6f2ad81303f26be6d7cd9b2471444f3

fix #10172

### CODE REVIEW

**Comment by erdembayar** [comment]
Idea from Advay `I'd prefer 'include vulnerable' and 'include prerelease' checkboxes `

**Comment by OliaG** [comment]
Yes, agree with [erdembayar](https://github.com/erdembayar), something like this would be great:
collapsing_versions

I think it's good to distinguish between known vulnerable versions and a pre-released ones, this way gives more explanation about the each, and I'd avoid using "unstable" in general, since it might set a bad sentiment.

Apologies from PM side for not giving you the mock-ups earlier :)

**Comment by erdembayar** [comment]
> Thank you for the PR!
> 
> I agree with [erdembayar](https://github.com/erdembayar), something like this would be great: collapsing_versions
> 
> I think it's good to distinguish between known vulnerable versions and a pre-released ones, this way gives more explanation about the each, and I'd avoid using "unstable" in general, since it might set a bad sentiment.

@Varorbc 
Could you be able to implement above proposal? Please let me know.

**Comment by erdembayar** [comment]
> Sorry, I don't have any extra time to keep working on this.

Based on this comment, I'm closing this PR, please feel free to continue the PR when you have time.

**Pull request closed without merging**
