### PR TITLE
lossless image optimization

### PR DESCRIPTION
**Pull request by chipitsine**

### CODE REVIEW

**Comment by skofman1** [comment]
What is the purpose of this PR?

**Comment by chipitsine** [comment]
the purpose is to reduce web traffic

**Comment by ryuyu** [comment]
Looks like this shrinks the image files in our documentation. 👍

**Comment by chipitsine** [comment]
oops, I missed your comment regarding dev branch.
I will reopen soon

**Comment by skofman1** [comment]
@chipitsine , our UI changed significantly since this PR was created. I apologize we didn't merge it sooner. You are welcome to add similar improvements to our new UI, promise to respond faster. 😃

**Comment by chipitsine** [comment]
any reason for responding faster ?

**Pull request closed without merging**
