### PR TITLE
Display markdown licence files as HTML

### LINKED ISSUE #7975: Embedded licenses files in MD are not encoded as HTML for display.
### Describe the bug

According to the specification embedded license files are accepted in either TXT or MD format.
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg#license

However, MD files are not converted to HTML for display on the site and are rendered as raw Markdown.

### To Reproduce
1. On this URL 'https://www.nuget.org/packages/SixLabors.ImageSharp/1.0.0-rc0001/License'

### Expected behavior

I would expect the markdown to be encoded as HTML.

### PR DESCRIPTION
**Pull request by rocklan**
This adds support for displaying licence markdown files as HTML. A few notes:

* The `ReadmeService.GetReadMeHtml` should probably be refactored to factor out the MD -> HTML conversion. I have run out of time to do this

* The `CommonMark` library has a weird bug that if a string begins with a BOM, it doesn't convert the first line properly. As a result I stripped it out and then it works ok. It looks like the version of CommonMark used is old, and the package is also depreciated, but I don't have time to fix this either.

* Arguably there could also be another test added for converting licence MD files to HTML, I also haven't done this 

Addresses https://github.com/NuGet/NuGetGallery/issues/7975

### CODE REVIEW

**Comment by dnfgituser** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8151) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8151) before we can accept your contribution.<br/><br/>:x: rocklan [sign now](https://cla.dotnetfoundation.org/NuGet/NuGetGallery?pullRequest=8151)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/NuGet/NuGetGallery?pullRequest=8151) it.</sub>

**Comment by zhhyu** [comment]
We are very excited to see your contributions! :smile:
Could we move the base branch to Dev? We always merge to the Dev branch firstly, and then merge to the main branch after we verify it. Thanks!

**Comment by rocklan** [comment]
Aha sure I can figure out how to do that. Do I need to abandon this PR?

**Comment by zhhyu** [comment]
Hi, @rocklan  I recommend that we send out another PR based on the Dev branch. We are continuously checking new fixes and features into the Dev branch, and it will be much easier for us to rebase your branch later when we decide to merge your changes. Thanks! :smile:

**Comment by rocklan** [comment]
I have tackled better this in another pull request so I'll abandon this one and create another one.

**Pull request closed without merging**
