### PR TITLE
Fix grammar in verify tool message

### PR DESCRIPTION
**Pull request by Eilon**

### CODE REVIEW

**Comment by zhhyu** [comment]
Thank you for your contributions!

**Comment by joelverhagen** [comment]
Thanks for the change @Eilon. I'll merge this in. We should talk offline about the long term strategy for this verification tool.

**Comment by Eilon** [comment]
Thanks! Happy to help however I can. I ran this tool as recommended by @karann-msft and it reported happiness to me.

**Comment by joelverhagen** [comment]
This fix was incorporated into https://github.com/NuGet/NuGetGallery/pull/7834.

The updated instructions for the tool are here:
https://github.com/NuGet/NuGetGallery/tree/master/src/VerifyMicrosoftPackage

I have initiated the integration of the official version of the tool into Arcade here:
https://github.com/dotnet/arcade/pull/4838

**Pull request closed without merging**
