### PR TITLE
Status

### PR DESCRIPTION
**Pull request by skofman1**
Fix for: https://github.com/NuGet/NuGetGallery/issues/5048

Screenshot:
image

### CODE REVIEW

**Comment by joelverhagen** [comment]
What does soft deleted look like? I think you may have an extra column.

**Comment by skofman1** [comment]
There is no change of behavior for delete:
image

Verified before sending this PR

**Comment by joelverhagen** [comment]
@skofman1, I think you have an extra column:
https://github.com/NuGet/NuGetGallery/blob/9076a6ff3de28f3d2f69b3ebe93627be6156979b/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L463-L466

**Comment by skofman1** [comment]
Fixed: https://github.com/NuGet/NuGetGallery/pull/5148

**Pull request merged**
