### PR TITLE
Don't delete Web UI test results and only delete minimal functional test results

### PR DESCRIPTION
**Pull request by joelverhagen**
Today, since we delete the Web UI test results, only the P2 Web UI results are available.

We can depend on the CI build configurations "Clean all build directories" setting to do the clean-up.

### CODE REVIEW

**Comment by joelverhagen** [comment]
> This is an improvement, but why do we need to delete the functional test results? Can't we depend on "Clean all build directories" for that as well?

I left it for local runs.

**Comment by scottbommarito** [comment]
@joelverhagen sounds good then!

**Comment by chenriksson** [comment]
@joelverhagen Just to confirm, leaving TestResults won't cause disk space issues on the build agents? Do agents remove the cloned repo once the run completes?

**Comment by joelverhagen** [comment]
> @joelverhagen Just to confirm, leaving TestResults won't cause disk space issues on the build agents? Do agents remove the cloned repo once the run completes?

AFAIK, the clean happens at the beginning of the build rather than at the end.

**Comment by joelverhagen** [comment]
Address https://github.com/NuGet/Engineering/issues/1253.

**Pull request merged**
