### PR TITLE
Add feature flag for temp keys and disable

### PR DESCRIPTION
**Pull request by chenriksson**

### CODE REVIEW

**Comment by skofman1** [comment]
why is it important to have a feature flag for this new API?

**Comment by joelverhagen** [comment]
> why is it important to have a feature flag for this new API?

This is my suggestion. Since this should not be deployed without proper coordination (e.g. it requires multi-repo and client-server integration), we should have an easy way to disable the feature if one of the dependencies does not land in time.

**Comment by skofman1** [comment]
I don't see risk in deploying the feature with the endpoint exposed. This is not something discover-able. Adding an on/off switch will require and extra deployment, and introduce additional process. Also, we will have an additional configuration value that will never be used in the long run. 
Thoughts?

**Comment by chenriksson** [comment]
Closing, will proceed w/o feature flag

**Pull request closed without merging**
