### PR TITLE
Fix org profile to show correct MFA status for site admins

### PR DESCRIPTION
**Pull request by shishirx34**

### CODE REVIEW

**Review by drewgillies — APPROVED** [review]
:shipit: ❤️

**Comment by drewgillies** [comment]
@shishirx34 There will need to be a documentation change on this, specifically in here: https://github.com/NuGet/Engineering/blob/main/Processes/ExternalStaff/ServerCustomerSupport/NamespaceReservationsExternal.md
It's a text change to bullet point ii under MFA. I can take care of it if you like, after this merges. Let me know.

**Comment by shishirx34** [comment]
Sounds good Drew. Will keep you posted.

**Comment by shishirx34** [comment]
@drewgillies - We should update the documentation once this fix is deployed to PROD. I don't want to create too much confusion until this fix is live. The current process would work no matter what at the moment.

**Pull request merged**
