### PR TITLE
[Organizations] Small UI fixes

### PR DESCRIPTION
**Pull request by scottbommarito**
"being deprecated" -> "deprecated":
image

Manage organization members table:
image

Transform page:
image

### CODE REVIEW

**Comment by chenriksson** [comment]
@scottbommarito looks fine to me, but could you give more details on the UI changes? Are the changes based on feedback from @anangaur or things you noticed that didn't render well on mobile?

**Comment by scottbommarito** [comment]
@chenriksson the feedback was from @ananguar

**Comment by skofman1** [comment]
Transform account is missing explanation text and documentation links. This is not a blocker for this PR, but it's a blocker for the feature.
// cc: @anangaur

**Comment by anangaur** [comment]
Can you reduce the gap in 1 to half and the gap with 2 and 3 to same as 1 (after reducing to half)
For number 4, center align (vertical)
image

**Pull request merged**
