### PR TITLE
Convert from WCF OData to Web API OData

### LINKED ISSUE #2557: Convert from WCF OData to Web API OData
Convert from WCF OData to Web API OData. This will allow us to squeeze query possibilities and reduce the surface area of the OData feeds.

### PR DESCRIPTION
**Pull request by maartenba**
This PR fixes #2557.

* V1, V2 and V2 curated feeds converted from WCF OData to Web API OData
* WCF OData feeds removed
* Caching on common search queries
* Batching

@xavierdecoster @yishaigalatzer @joyhui @johnataylor Feel free to checkout this branch and perform some testing on the OData endpoints. Any bug / issue you find is very welcome!

(this PR supersedes https://github.com/NuGet/NuGetGallery/pull/2583 as a clean rebase)

### CODE REVIEW

**Comment by xavierdecoster** [comment]
Looks good to me! :shipit:

**Comment by maartenba** [comment]
@yishaigalatzer @joyhui @johnataylor Let me know if/when to ship.

**Comment by skofman1** [comment]
I'm actually @skofman1

**Pull request merged**
