### PR TITLE
Add AppVeyor CI config

### PR DESCRIPTION
**Pull request by 304NotModified**
supersedes #2707

Addition of a config file to build successful with [AppVeyor CI](https://ci.appveyor.com). 
This is not meant as a replacement of the current build server, TeamCity CI.

Building with AppVeyor, next to TeamCity gives the following benefits:

- In a PR it's clear if the submitted code compiles and won't break any unit tests
- The build and test status is clear en public visible
- It looks professional IMO ;)

downsides:

- None

Example output: 
https://ci.appveyor.com/project/304NotModified/nugetgallery/build/1.0.6

This PR only creates a config file. To add the AppVeyor webhook to GitHub, AppVeyor should be integrated to this repository. This can be done by the following (simple) steps: 

1. Sign in to AppVeyor (https://ci.appveyor.com)
1. Click button "new project"
1. GitHub / select repository, click "add"
1. Click button "new build"
1. Build
1. Add AppVeyor webhook (should be automatically added? But failed last time to me)
1. (optional) Add badge with build/test status :)

### CODE REVIEW

**Comment by 304NotModified** [comment]
@maartenba 

Is it a possibility to enable the web hook as described above? (the steps)

Because in https://github.com/NuGet/NuGetGallery/pull/2716 I failed an unit test, and that is currently not clear. 

See: https://ci.appveyor.com/project/304NotModified/nugetgallery/build/1.0.13

**Comment by maartenba** [comment]
Would prefer to have an AppVeyor account under the NuGet name. Let me check and see what we can do.

@yishaigalatzer Okay if we create an official NuGet Gallery AppVeyor build so that we can report build status publicly?

**Comment by yishaigalatzer** [comment]
I’m ok with it, the priority for this is very low.

**Comment by maartenba** [comment]
Made a few changes to `appveyor.yml` and added build badge to README.

**Comment by 304NotModified** [comment]
Nice! I'm pretty sure you guys will benefit from this feature :)

**Comment by maartenba** [comment]
The webhook to our build is also active - check the README for build badge :)

**Comment by 304NotModified** [comment]
Hey @maartenba ,

I saw the build badge :)

But the web hook isn't working? I don't see it in the PR, see https://github.com/NuGet/NuGetGallery/pull/2723

We need to see something like this:
image


We have successfully configured it like this:

image

**Comment by maartenba** [comment]
@csharpfritz can you check if the hook on the gallery fired successfully?

**Comment by maartenba** [comment]
Hook has been updated.

**Comment by 304NotModified** [comment]
Strange that it still doesn't work :(

see https://github.com/NuGet/NuGetGallery/pull/2728

**Comment by maartenba** [comment]
Does AppVeyor need anything special to enable status reporting to GitHub? I suspect that is what is missing here.

**Comment by 304NotModified** [comment]
Only the web hook AFAIK.

**Comment by maartenba** [comment]
Will check with them.

**Comment by 304NotModified** [comment]
You need to disable this:

image

I enabled it on NLog, and then also the webhooks were not working.

**Comment by maartenba** [comment]
@csharpfritz Can you edit the above for the gallery GitHub repo? It's an organization setting it seems.

**Comment by yishaigalatzer** [comment]
There are no restrictions today - 

for any required changes in policies of the github site, please work with me.

**Comment by 304NotModified** [comment]
> There are no restrictions today -
> 
> for any required changes in policies of the github site, please work with me.

I don't understand what you mean with this.

Anyway, to make it more clear I have the following questions

1. Is it clear what isn't working?
2. Do you know how to test it?
3. Any idea how to fix it?

**Comment by maartenba** [comment]
Working on it :)

**Comment by 304NotModified** [comment]
:+1:

**Pull request merged**
