### PR TITLE
[MSA] Add support for deprecating password logins - schema changes

### PR DESCRIPTION
**Pull request by shishirx34**
With the new changes coming in for AADv2, we will be deprecating user password logins. Since this will be a phased roll out, we need to mark certain accounts with deprecated passwords, for the accounts that will be migrating to the AADv2. 

Update:
Going forward, we will be deprecating password login for the users who have migrated (linked) account to MSA/AAD. These users will not be able to login with the password anymore. The UI flow in account settings, for Enabling/disabling passwords will be removed[note that this will only be for users whose password login has been deprecated by linking to MSA/AAD] and shown that these users have to use the Microsoft account to login. We cannot deprecate a user's password login until they have linked MSA/AAD account to the NuGet account. Once they have done it then we will block them from enabling/disabling the password login. This is as per @anangaur's specs. This will discourage regular users from using password login.

### CODE REVIEW

**Comment by chenriksson** [comment]
@shishirx34 Deprecation is for @ microsoft.com? Could we use the same config whitelist as organization migration as opposed to a DB schema change?

**Comment by shishirx34** [comment]
It will be for all the users who have linked their MSA/AAD accounts after the fact, not just the @microsoft.com accounts. We can't deprecate users who haven't linked their accounts. We need the schema change.

**Comment by skofman1** [comment]
@shishirx34 , can you provide more details about the user experience we are implementing here?

**Comment by scottbommarito** [comment]
Should we also add a column here to store a token for when a user whose password was deprecated tries to regain access to their account?

**Comment by scottbommarito** [comment]
Spoke with @shishirx34 offline, it's not necessary.

**Comment by shishirx34** [comment]
@skofman1 - added more details to the description.

**Comment by shishirx34** [comment]
I had discussion with @anangaur and @scottbommarito, and we will be simplifying this some more. We don't really need this PR anymore. The way to go around would be to remove the password login completely for the users who change/link to the MSA/AAD account and from the account settings page, remove the node for password login. The way to recover a password login would be forgot password flow.

**Pull request closed without merging**
