### PR TITLE
Avoid InternalServerError and capture exception on OData serialization errors

### PR DESCRIPTION
**Pull request by xavierdecoster**

### CODE REVIEW

**Comment by joelverhagen** [comment]
Why isn't internal server error the right thing here? What happens after we swallow the exception?

**Comment by scottbommarito** [comment]
I think, ideally, if the search service hijack fails, it should fall back to the database. If the database fails, it should 500. Does this fix make neither path return 500?

**Comment by xavierdecoster** [comment]
We are already serializing the OData response to the client when this exception happens, so not able to fallback in any way. Fallback behavior should be captured earlier in the pipeline and is tracked by issue https://github.com/NuGet/NuGetGallery/issues/3826 (including the fallback to db suggestion).

However, I'm not sure what other HTTP status code to return here, so perhaps we should just continue returning HTTP 500 then... in which case I just re-throw the exception after sending it to AI. Makes sense? If so, I'll adjust to re-throw instead.

**Comment by joelverhagen** [comment]
I think we should rethrow. It's okay to throw 500s if something truly exceptional is happening. This seems like one of those cases to me. We should certainly have visibility on the exception, which you have added.

**Comment by xavierdecoster** [comment]
Re-throwing the exceptional exception :) https://github.com/NuGet/NuGetGallery/pull/3831/commits/065eb8b929705ef88182bf23efe3250d3091a779

**Comment by skofman1** [comment]
I found a way to catch all exceptions. Need to test it a bit more. Will send details.

**Comment by skofman1** [comment]
https://docs.microsoft.com/en-us/aspnet/web-api/overview/releases/whats-new-in-aspnet-web-api-21#global-error

**Comment by xavierdecoster** [comment]
Superseded by https://github.com/NuGet/NuGetGallery/pull/3833

**Pull request closed without merging**
