### PR TITLE
[Dark Mode] Fix table row colors in dark mode

### PR DESCRIPTION
**Pull request by martinrrm**
Wrong style for some table rows in the package readme section.
### Before
image

### After
image
image

Addresses https://github.com/NuGet/NuGetGallery/issues/10065

### CODE REVIEW

**Comment by erdembayar** [comment]
Please add repair work item link?

**Review by erdembayar — APPROVED** [review]
Thanks

**Review by drewgillies — APPROVED** [review]
🚀

**Comment by martinrrm** [comment]
Is the CI really running? 😟

**Pull request merged**
