### PR TITLE
VerifyPackage page with more information

### PR DESCRIPTION
**Pull request by robertmuehsig**
As reported in this issue https://github.com/NuGet/NuGetGallery/issues/1570 I added a few more package details on the verify package page:

- MinClientVersion
- Language
- DeveloperDependency
- FrameworkAssemblies
- Dependencies

(ignore the glimpse bar - I choose a poor screen capture plugin ;))

Example with this package https://www.nuget.org/packages/Microsoft.Net.Http/2.2.27-beta results in:
image

https://www.nuget.org/packages/MvvmLight/
image

And one "devdependency" package https://www.nuget.org/packages/StyleCop.MSBuild/:
image

### CODE REVIEW

**Comment by xavierdecoster** [comment]
@robertmuehsig can't merge the PR as is as I'm getting an exception due to the missing DevelopmentDependencyProperty (exception thrown at `EditPackageService.GetPendingMetadata` line 27).

Would be good if you could fix that one. Even better if you could also tackle [this related issue](https://github.com/NuGet/NuGetGallery/issues/2244) to make it editable :)

Happy to take it in once fixed.

**Comment by xavierdecoster** [comment]
@robertmuehsig Also, in order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. https://cla2.dotnetfoundation.org.

**Comment by robertmuehsig** [comment]
Will look at it, but if I remember correctly the edit DevDependency needed a DB Migration, that's why it was just "read-only", but I will check it an leave a comment on the other issue. Thanks for looking into it.

**Comment by robertmuehsig** [comment]
So - I had time to look again at this PR and now I remember the problem.

@xavierdecoster I guess you are seeing this exception:
image
Now my comment from above makes perfect sense:
"But to get this into the database I also need to change the PackageEdit Entity and the EditPackageService - but in the first step this field needs to be in the database. Any convention how to create a new migration? 
With this in place the edit developent dependency issue should be resolved very quickly #2244"

I added a new property "DeploymentDependency" like "RequireLicence" but I need a to apply a database migration, because the actual package is not changed (as far as I know) - the edit stuff is saved in the database.

As questioned above (and with the new NuGet.org already in the making) : Should I just make a new database migration for the new property or should I leave the property as "read only"?
I would create a new database migration in the same programming style as the other db migrations.

**Comment by xavierdecoster** [comment]
@robertmuehsig that is exactly the issue I'm seeing :)

I guess you mean "DevelopmentDependency" instead of "DeploymentDependency", right?
Will get back to you on the db migration question.

**Comment by robertmuehsig** [comment]
Woops - yes - DevelopmentDependency ;)

**Comment by maartenba** [comment]
(fyi) @robertmuehsig Just in case you want to create a migration: from the package manager console, just run `Add-Migration DevelopmentDependencyEditable`. EF will make the necessary files.

**Comment by robertmuehsig** [comment]
Ay! Just give me a hint if I should create the migration and finish this PR + the fix for the editable DevDependency and I try my best. Database changes are sometimes nasty for the deployment-team, so I didn't want to rush too quickly.

**Comment by maartenba** [comment]
@robertmuehsig I'll probably take care of the deployment, thanks for thinking of me :)

**Comment by robertmuehsig** [comment]
:+1:  Then I will try my best not to screw up the NuGet.org database ;)

**Comment by robertmuehsig** [comment]
Ok, it seems I have found all missing pieces and it seems to work in my branch:

Edit Page:
image

Detail Page:
image

Verify Page:
image

Tested with the LibLog (DevDependency == true) package https://www.nuget.org/packages/LibLog/4.1.1

I needed two migrations, because in the first run I didn't had the DevelopmentDependency in the Package Entity, but I guess this could be merged.

**Comment by maartenba** [comment]
Any chance you can squash your commits and rebase on `dev` branch?

**Comment by robertmuehsig** [comment]
Sure, but my Git-Voodoo is too low. Could you give me a hint how to do that?

**Comment by maartenba** [comment]
This could help: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by yishaigalatzer** [comment]
Is the migration required only for the 'DevelopmentDependency'? Can we leave it out (sorry being super risk averse).

**Comment by robertmuehsig** [comment]
@yishaigalatzer Yes, as far as I know you track the "editable" fields (and the values) in the database. In the original PR (or from another issue? It's a long time ago) my first try was just to leave it as read-only, but - just like the other fields - it should be editable, that's why I created the DB migrations. 
Without the DB migrations the DevDependecy would only be "read-only". I guess I could rebase the Pull Request to this point in time https://github.com/NuGet/NuGetGallery/pull/2242#issuecomment-108760047 and just finished the PR without the DB migration and leave this field as read-only (in the first step).
Just let me know how you would like to handle the PR.

**Comment by robertmuehsig** [comment]
Woops... wrong button ;)

**Comment by maartenba** [comment]
Let's make it read-only for now? If we'd make it editable we'd need a fix on the jobs-side of things as well.  We can revisit making it editable later.

**Comment by robertmuehsig** [comment]
Ok - I will try my best.

**Comment by maartenba** [comment]
Thanks @robertmuehsig - you rock!

**Comment by 304NotModified** [comment]
@robertmuehsig I like this PR. I would be great if the last things get fixed! Need help on this?

**Comment by robertmuehsig** [comment]
Hi @304NotModified - as you might have seen: I didn't found any time to work on this.

Because my Git Skills are very low, my plan was to create a new PR with the newest dev-source and make all changes except for the part with the needed Database Migration.

Idea:
- Show all dependencies & meta data
- Show DevDependency as Read-Only (so no DB upgrade is needed)

I think you could reuse most of the code - there are only a couple of changes I made for the DevDependency database stuff.

If you would like to work on this - go ahead :)

**Comment by 304NotModified** [comment]
@robertmuehsig, @maartenba 

FYI, It's really easy to squash commits in tortoisegit!

http://stackoverflow.com/a/21306306

**Comment by robertmuehsig** [comment]
With the recent merge of https://github.com/NuGet/NuGetGallery/pull/2834 I think this PR can be closed. The "editable" DevDependency is a greater issue, because it needs database changes.
I would try to show the "DevelopmentDependency" (like this https://github.com/robertmuehsig/NuGetGallery/blob/1570-verifypage/src/NuGetGallery/Views/Packages/DisplayPackage.cshtml#L282 ) status via a new PR.

**Pull request closed without merging**
