### PR TITLE
[ReleasePrep][2024.02.27] RI of dev into main

### PR DESCRIPTION
**Pull request by zhhyu**

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Review by lyndaidaii — APPROVED** [review]

**Comment by lyndaidaii** [comment]
I am working on one change and also want that change to be deployed. Please hold it on once my change is in.

**Comment by lyndaidaii** [comment]
Have my changes now in dev. feel free to deploy

**Comment by lyndaidaii** [comment]
Lana's changes were in main not in dev, I think we could do another MR from main to dev again. @Lanaparezanin

**Comment by lyndaidaii** [comment]
Here is PR that bring changes from main to dev with Lana's change: https://github.com/NuGet/NuGetGallery/pull/9838

**Review by lyndaidaii — DISMISSED** [review]

**Review by lyndaidaii — DISMISSED** [review]

**Review by advay26 — APPROVED** [review]

**Review by lyndaidaii — DISMISSED** [review]

**Review by advay26 — APPROVED** [review]

**Pull request merged**
