### PR TITLE
Selectively render the vulnerable element on manage packages page

### PR DESCRIPTION
**Pull request by joelverhagen**
This significantly improves performance for the manage packages page. For a user with 1000 package IDs, it went from a 7 second page render time to 3 seconds.

There are two changes:

- **Significant:** don't render the vulnerable element when the package is not vulnerable. Previously it was hidden but still in the DOM causing the expensive `setPopovers` method to run for each package.
- **Small improvement:** use `this` instead of `$(this).get(0)` to get the DOM element. (improved cumulative `setPopovers` execution time from 4.381 seconds to 4.089 seconds.

**Perf before:**
image

**Perf after:**
image

(tons on `setPopovers` calls removed)

The page is still slow, but more usable than before.

Progress on https://github.com/NuGet/NuGetGallery/issues/5877

### CODE REVIEW

**Review by agr — APPROVED** [review]

**Review by drewgillies — APPROVED** [review]
Wonderful! :)

**Comment by drewgillies** [comment]
@joelverhagen I'm curious - was this invetsigation in response to a perf complaint, observation or hunch?

**Comment by joelverhagen** [comment]
> @joelverhagen I'm curious - was this invetsigation in response to a perf complaint, observation or hunch?

Sorry, missed your comment prior to merge. It was something I noticed while accepting an ownership request on behalf of @clairernovotny 😃. She mentioned it's slow for her too.

**Comment by drewgillies** [comment]
@joelverhagen Discussion point only--I wasn't blocking on it, was just wondering how it surfaced. Great improvement.

**Pull request merged**
