### PR TITLE
Update to accounts page to take into account the need for -Source parameter

### PR DESCRIPTION
**Pull request by harikm86**
https://github.com/NuGet/Home/issues/2504#issuecomment-216063943 opening in reference to this issue

### CODE REVIEW

**Comment by harikm86** [comment]
@xavierdecoster @maartenba

**Comment by maartenba** [comment]
I tink source should be https://www.nuget.org/api/v2/package ? Or does the client add that suffix?

**Comment by harikm86** [comment]
damn it, copy paste mistake. let me fix it. Should have double checked the diff. I will use the v3 link though.

**Comment by harikm86** [comment]
@xavierdecoster can you do a quick review of the change. Also, since this is not totally static content, what do I need to do to push this to production?

**Comment by rrelyea** [comment]
:shipit:

**Comment by xavierdecoster** [comment]
@harikm86 post-vacation squirrel! :shipit: This change needs a full gallery deployment.

**Comment by harikm86** [comment]
@xavierdecoster I know, didnt want to do it untill you were back :). Should i do it or do you want to?

**Comment by xavierdecoster** [comment]
@harikm86 I'll take it

**Comment by harikm86** [comment]
Thanks.

Sent from Outlook<https://aka.ms/kr63o9> on iOS

________________________________

**Pull request merged**
