### PR TITLE
Update Download table heading

### PR DESCRIPTION
**Pull request by toseni**
PR for #8479

### CODE REVIEW

**Comment by toseni** [comment]
Before:
image

After:
image

`Downloads` column shifts to the left. 
Should I make sure that it does not shift?

**Comment by camigthompson** [comment]
@clairernovotny Could you take a look at the proposed changes in the screenshot above? Thanks!

**Comment by toseni** [comment]
Used `table-layout: fixed` to make the shift better. 
Initial:
image
After:
image

**Review by clairernovotny — APPROVED** [review]

**Review by camigthompson — APPROVED** [review]

**Review by camigthompson — APPROVED** [review]

**Review by clairernovotny — APPROVED** [review]

**Comment by toseni** [comment]
Sorry, seems that I haven't completely followed your contributing guidelines.

**Pull request merged**
