### PR TITLE
Change Link in h2 Color from Black to Blue

### PR DESCRIPTION
**Pull request by Goodyear2017**
Change Link in h2 Color from Black to Blue
Bug link: https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1985625

### CODE REVIEW

**Comment by erdembayar** [comment]
@Goodyear2017 
If possible please include screenshot for the UI change.

**Comment by Goodyear2017** [comment]
@erdembayar Please see the screenshot for the "sign in" color change
image

**Review by erdembayar — APPROVED** [review]

**Review by ryuyu — APPROVED** [review]

**Comment by Goodyear2017** [comment]
Is adding underline to the link text an acceptable solution?

**Comment by Goodyear2017** [comment]
@martinrrm I had made the css change,  adding underline to the link in h2. If underline is not acceptable, please suggest something.

**Comment by agr** [comment]
Now looking at it, the whole last section looks weird. Until then the format is: question in the header, answer/suggestion in the body. In the last item there is question and suggestion in the header and then another question and suggestion in the body...
I think we need to rework the page itself a bit.

@JonDouglas any thoughts?

**Comment by agr** [comment]
@ryuyu, haven't we been flagged for horizontal scrollbars in the past?

**Comment by JonDouglas** [comment]
We shouldn't put special decoration on headers if possible. We can instead just put instructions in the answer portion to instruct the user to sign in with link instead. I'd recommend removing the link in the header in this case and putting a small sentence to describe how to best contact and whether or not one needs to login to do that.

**Comment by Goodyear2017** [comment]
@JonDouglas  I thought removing the link from the h2 header is the best solution. You will need to give me the content that will replace what is currently there.

**Comment by martinrrm** [comment]
@Goodyear2017 @JonDouglas I have a fix for this issue, the color of the link, in this PR https://github.com/NuGet/NuGetGallery/pull/9914, if we still believe we need to change the text please let me know.

**Comment by Goodyear2017** [comment]
@martinrrm It would be fine just change the text color. However I didn't see the change in either local environment or production.

**Pull request closed without merging**
