### PR TITLE
Move email message implementations from ServerCommon to NuGetGallery

### PR DESCRIPTION
**Pull request by xavierdecoster**
Follow-up to https://github.com/NuGet/Engineering/issues/1897

This moves the email message implementations into either `NuGetGallery.Core` or `NuGetGallery`.
The dependency to `NuGet.Services.Entities` is now explicit again for `NuGetGallery.Core`, as `NuGet.Services.Messaging.Email` no longer depends on it.

Note to reviewers: the newly added files are unchanged and originate from ServerCommon. Except for the newly introduced `EmailRecipientsHelper`. The static methods on `EmailRecipientsHelper` used to be in `EmailRecipients`, but required a dependency to `NuGet.Services.Entities`. Therefor, I moved it into `NuGetGallery.Core`, where it can be shared along with the shared email messages.

TODO: need to consume new to-be-created master-release of ServerCommon packages.

@skofman1 can this ServerCommon 2.37.0 release be created?

### CODE REVIEW

**Comment by xavierdecoster** [comment]
There's a currently build failure due to dependency resolution conflict. Consuming the new ServerCommon stable packages will likely fix that.

**Comment by scottbommarito** [comment]
@xavierdecoster - the build failure is because both `NuGet.Services.Validation` and `NuGet.Services.Messaging.Email` depend on `NuGet.Services.Contracts`. You can either create `2.37.0` (and make sure to bump the version in the build definition so it starts building `2.38.0-x`) or just use `2.37.0-master-2208195`.

**Comment by xavierdecoster** [comment]
Moving out the unit tests elsewhere seems trickier than expected. We have a bunch of useful classes in `NuGetGallery.Facts\Framework` that could be shared cross-repository. Candidate for `ServerCommon` project? (e.g. `NuGet.TestFramework`?)

For instance, the unit test class `MessageServiceFacts.TheSendSymbolPackageAddedNoticeMethod` inherits `TestContainer`.

**Comment by xavierdecoster** [comment]
This also means Orchestrator will take a dependency on `NuGetGallery.Core` for the following types:
* `PackageValidationSetExtensions`
* `EmailRecipientsHelper`
* `PackageAddedMessage`

**Comment by xavierdecoster** [comment]
When upgrading to version `2.37.0`, I noticed a change is needed to `CachingSecretReader` first, as `ISecretReader` has changed (new method `GetSecretObjectAsync(string)` needs to be implemented).

@skofman1 you know who did this change and can handle the update in the gallery? Would be good to get that one into dev first so I can rebase my change on top :)

**Comment by chenriksson** [comment]
@xavierdecoster That change was made by a dev on the powershell gallery team, in order to facilitate auto-rotation of secrets. Since I'm familiar with that change, I can handle the update in Gallery if you'd like... can look today.

**Comment by xavierdecoster** [comment]
@chenriksson great! thanks :)

**Pull request merged**
