### PR TITLE
Feature: Add message for AddOwner request

### PR DESCRIPTION
**Pull request by robertmuehsig**
UI, message-service & tests enhanced for "message"

image

Email body will look like this:

```
The user 'admin' wants to add you as an owner of the package 'OpenXMLSDK-MOT'.
If you do not want to be listed as an owner of this package, simply delete this email.

To accept this request and become a listed owner of the package, click the following URL:

[https://nuget.localtest.me/packages/OpenXMLSDK-MOT/owners/tester1/confirm/hqVPnrJcMiOBD06SkBFOog2](https://nuget.localtest.me/packages/OpenXMLSDK-MOT/owners/tester1/confirm/hqVPnrJcMiOBD06SkBFOog2)

The user 'admin' added the following message for you:

'asda sd asd asd ,,, &lt; .&gt;&gt;'

Thanks,
The NuGet Gallery Team
```

`'asda sd asd asd ,,, &lt; .&gt;&gt;'` => the given message

The message itself will be html encoded and will be sent in the email.
The message will not be stored in the db, which is ok I think.
Related to this https://github.com/NuGet/NuGetGallery/issues/328

### CODE REVIEW

**Comment by skofman1** [comment]
@jonwchu ?

**Comment by skofman1** [comment]
@robertmuehsig , the feature looks great, and we are interested in taking it!
Can you please send a PR against dev branch? We can't merge changes directly to master, since our process is: push changes to dev, verify them in dev environment, push to master, verify again, deploy to staging and production.

Thank you!

**Comment by robertmuehsig** [comment]
I just changed the base branch to dev - do I need to do anything else?

**Comment by skofman1** [comment]
@xavierdecoster , @yishaigalatzer , another pair of eyes?

**Comment by xavierdecoster** [comment]
LGTM once the review comment by @skofman1 is addressed

**Comment by robertmuehsig** [comment]
I changed the way the email body is generated. The email version without the user message will look like this:

```
The user 'Existing' wants to add you as an owner of the package 'CoolStuff'.
If you do not want to be listed as an owner of this package, simply delete this email.

To accept this request and become a listed owner of the package, click the following URL:

[http://example.com/confirmation-token-url](http://example.com/confirmation-token-url)

Thanks,
The Joe Shmoe Team
```

And with the user message:

```
The user 'Existing' wants to add you as an owner of the package 'CoolStuff'.
If you do not want to be listed as an owner of this package, simply delete this email.

To accept this request and become a listed owner of the package, click the following URL:

[http://example.com/confirmation-token-url](http://example.com/confirmation-token-url)

The user 'Existing' added the following message for you:

'Hello World!'

Thanks,
The Joe Shmoe Team
```

Unfortunately I had some issues with Git and couldn't combine it to one commit. Also it seems that VS made some small spacing changes - nothing dramatic, but if you with a "cleaner" PR I would create a new one and more or less copy over the changed parts.

**Comment by scottbommarito** [comment]
@robertmuehsig It's fine if it's in multiple commits for the PR, but if you could squash the commits when you merge that would be great.

@jonwchu Does the new email body look good?

**Comment by yishaigalatzer** [comment]
He can't merge...

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by scottbommarito** [comment]
My bad, will update the comment, thanks.

**Pull request merged**
