### PR TITLE
Add github information on the package page

### PR DESCRIPTION
**Pull request by richorama**
Two node.js applications, one to look at all nuget packages, determine which have github URLs and add these to an azure queue. The second reads from the queue, and uses the github API to retrieve repo information and a rendered readme.

Instructions are provided for installing and running.

### CODE REVIEW

**Comment by richorama** [comment]
ref #2925

**Comment by maartenba** [comment]
Looks simple enough. What's the "special cases" file intended for?

Will discuss this one a bit internally, thanks already!

**Comment by richorama** [comment]
1. The special cases file is intended to override the capture of the GitHub URL from the package information. This means you can 'hard code' the github repo. I used this for popular packages where the project URL was not the github repository, and when the repository has moved (i.e. new owner or new name) as my code didn't used to handle this case very well (it does now, but this is a useful optimisation). The special cases file can be removed, and if this feature does make it into production, we should encourage people to point to their github repo correctly.
2) I ran my script weekly, so the readme could be behind. However, readme files don't tend to change that much, and you could add a 'last crawled' date to the package page so people understand it's a background process. I suggest that when a new package version is published to nuget, you add a message to the queue to schedule the capture of the readme (it's a good signal that something has changed).

What I have pushed so far is a quick way of getting some data into blob storage, we'd need to make some changes (or rewrite) at some point.

The next piece is to show the github information and readme on the package page in the gallery. I'll start to build that out in the next few days...

**Comment by maartenba** [comment]
Feel free to hold off for a few days, going to have some discussions with the team first to see ow we want to land this in the NuGet product. (love your drive! :))

Although making sure the Markdown can be rendered properly is probably a good effort to have...

**Comment by maartenba** [comment]
We may take it, but we'd need C# code on all sides :) We have a job runner that could run the back-end job without issue - if you could reduce that one to one or two classes (and any helper classes needed, of course) with a "Run" method we can plug it into the job runner.

**Comment by richorama** [comment]
ok, will do.

**Comment by richorama** [comment]
BTW, do you know the best way to get to a list of all the package IDs from C#? 

I can't see support for this in https://github.com/nuget/nuget.client (some documentation on this repo would also be nice).

**Comment by maartenba** [comment]
We currently don't have such thing in the V3 API (and maybe we should have it). You can use the NuGet List command as an inspiration https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Clients/NuGet.CommandLine/Commands/ListCommand.cs

Alternatively, feel free to code against an `IEnumerable<string>` for package id's for now - we should be able to provide that for sure.

**Comment by maartenba** [comment]
After giving this some more thought (and internal discussions), we'd like to do a minimal implementation of this first, where the package details page in the gallery is responsible for fetching the readme info (and if rate limiting does not allow, then no readme is displayed). The readme can then be cached for a few days, but we don't want to store it forever - nor do a weekly scan for all packages.

**Comment by richorama** [comment]
ok, I'll spike that out.

**Comment by richorama** [comment]
Work in progress, but this shows some stats from github:

image

The C# GitHub API doesn't seem to support the readme location or the markdown rendering, I'll follow it up with them..

**Comment by richorama** [comment]
now with readme \o/

screenshot 2016-03-31 16 43 07

**Comment by richorama** [comment]
... of course, the Entity Framework package's project URL doesn't point to the GitHub URL, I hacked it to capture the screenshot.

**Comment by maartenba** [comment]
Think @Haacked will like this, too :-)

**Comment by richorama** [comment]
I hoped that @Haacked might be able to raise the API limits :¬P

**Comment by maartenba** [comment]
Wondering how easy (or not :-)) adding Bitbucket would be?

**Comment by richorama** [comment]
Good question. I'll have a try.

**Comment by richorama** [comment]
Hmm, the bitbucket API is a bit more limited:

https://confluence.atlassian.com/bitbucket/repository-resource-423626331.html

As far as I can tell, the differences are:

* No stars (bitbucket doesn't have them)
* No 1st class way of retrieving and rendering the readme (you could do it by downloading raw files though)
* Fork and Issue counts are not summarised, you have to query them all.

I evaluated codeplex a while ago as well. That API is fairly useless: https://www.codeplex.com/site/developers/api/projects

**Comment by maartenba** [comment]
Maybe just the README could work for BitBucket?

**Comment by richorama** [comment]
...now with added bitbucket.

screenshot 2016-06-02 14 10 32

**Comment by richorama** [comment]
Please note that this was built using a fork of SharpBucket: https://github.com/richorama/SharpBucket
The binary has been added to the `libs` folder whilst I wait for [this PR](https://github.com/MitjaBezensek/SharpBucket/pull/33) to be accepted.

**Comment by maartenba** [comment]
This is awesome! Let me check this with the team first and then I'll get back to you. I'm a fan ❤️

**Comment by jdom** [comment]
This is great!

**Comment by maartenba** [comment]
@richorama The implementation looks good, the feature looks good and the team loves it :-)

That said, we're going to let this one rest for a little longer. We have some operational work that is taking priority right now and want to give this one the attention it deserves once the dust settles.

Keep up the good work, this is awesome stuff!

**Comment by robertmuehsig** [comment]
Is there anything we could do to get this awesome feature merged?

**Comment by skofman1** [comment]
We are planning some UI related improvements soon. We can review this feature again after that.

**Comment by 304NotModified** [comment]
> The implementation looks good, the feature looks good and the team loves it :-)

How could this take years then? ...

**Comment by 304NotModified** [comment]
> We are planning some UI related improvements soon. We can review this feature again after that.

bump @skofman1

**Comment by joelverhagen** [comment]
I'm going to close this PR. I love the ideas involved in this PR, however!

If anyone is interested in taking this idea forward, I think it would be best to have a formal proposal as described here:
https://github.com/NuGet/Home/tree/dev/meta#nuget-proposal-process

This would allow us (NuGet team) and the community to discuss the ideas first and then later approach the code.

For reference, our current GitHub integration is:

- A background job that periodically queries for package references in .csproj files found on top C# GitHub projects. This enables the "Used by" tab to show what GitHub repos use a given package.
- Embedded readme with Markdown support -- much like GitHub repo READMEs (improvements tracked by https://github.com/NuGet/NuGetGallery/issues/8837)
- Repository URL link on the package details page, linking back to GitHub repos

The https://github.com/NuGet/NuGetGallery/issues/2925 issue still tracks further integrations.

**Pull request closed without merging**
