### PR TITLE
Keyboard focus is not clearly visible 

### PR DESCRIPTION
**Pull request by lyndaidaii**
Summary of the changes (in less than 80 characters):

Problem:  Keyboard focus is not clearly visible because of overflow was set to hidden. 

Fix: Changed to visible since the button name length is fix, won't be overflow.

For "Eidt, Regenerate, Delete" buttons, it's ok to 

Addresses https://github.com/NuGet/Engineering/issues/4827

### CODE REVIEW

**Review by advay26 — APPROVED** [review]

**Comment by agr** [comment]
Could you please post screenshots?

**Comment by lyndaidaii** [comment]
> Could you please post screenshots?

not able to provide with the screenshots since keyboard interaction. video might work. let me upload it.

**Comment by agr** [comment]
As far as I understand, this
image
gets changed to this
image

Given that `.package-list` class name seems a bit out of place and that we have an explicit `overflow-y: hidden` for `.package-list li` selector
https://github.com/NuGet/NuGetGallery/blob/0931f8b8176fc59d6bf0d47dee2baf686db3bea4/src/Bootstrap/less/theme/base.less#L367
I would guess that combination of elements is used elsewhere, too. I wonder if the focus indication is broken there, too.

**Comment by agr** [comment]
OK, it is on package list page and respective elements there are not focusable.

**Review by agr — APPROVED** [review]

**Pull request merged**
