### PR TITLE
Cleanup: Unused files removed

### PR DESCRIPTION
**Pull request by robertmuehsig**
I discovered some old files, which doesn't seemed to be used anywhere and are safe* to delete.

Goal: Just cleaning up the repo...

* The solution does build and I looked through the different Powershell/CMD-Scripts and didn't found any hint that these files are used.

### CODE REVIEW

**Comment by maartenba** [comment]
We have a few other services that make use of the HashCodeCombner - can you revert that one from the PR?

**Comment by robertmuehsig** [comment]
Is this file included as a link in other projects? Didn't found any reference to it.

**Comment by maartenba** [comment]
We have a NuGet on an internal build server that includes it

**Comment by robertmuehsig** [comment]
Sneaky ;) I will take a look at it tonight.

**Comment by robertmuehsig** [comment]
done :)

**Comment by skofman1** [comment]
Was committed to dev.

**Pull request closed without merging**
