### PR TITLE
update term used for .NET tools

### PR DESCRIPTION
**Pull request by adamralph**
As per the [linked document](https://aka.ms/global-tools), these are now referred to as ".NET tools" —

> How to manage .NET tools
> 
> A .NET tool is a special NuGet package that contains a console application.

### CODE REVIEW

**Review by drewgillies — APPROVED** [review]

**Comment by joelverhagen** [comment]
@wli3 - can you check the wording here? The command _does_ install as a global tool but it seems like the "Core" team is being dropped. The message looks like this today:


Example: https://www.nuget.org/packages/dotnet-reportgenerator-globaltool/
image


@augustoproiete - it looks like your proposed UI (https://github.com/NuGet/NuGetGallery/issues/8373) covers this change, right? I think with your tab name enhancement to say "global" vs. "local", we don't need to say "global" in the subtext.

**Comment by augustoproiete** [comment]
@joelverhagen Correct. The second bullet point on #8373 suggests the exact same wording that this PR is proposing (which LGTM). The tab enhancement would be to help distinguish global vs local.

**Comment by wli3** [comment]
@kathleendollard has the call. But I think this change is good.

**Comment by skofman1** [comment]
@adamralph , thanks for creating the PR and your proposal. Since @augustoproiete's suggestion in https://github.com/NuGet/NuGetGallery/issues/8373 addresses your concern and provides a more complete solution, we will proceed with that.

**Comment by adamralph** [comment]
https://github.com/NuGet/NuGetGallery/issues/8373 is just an issue and is still being discussed. Why not merge and deploy this in the meantime? Sure, it doesn't have all the other stuff that https://github.com/NuGet/NuGetGallery/issues/8373 is proposing, but it's still a valuable change on it's own no?

**Pull request closed without merging**
