### PR TITLE
Update methods

### PR DESCRIPTION
**Pull request by KhanbalaRashidov**
Summary of the changes (in less than 80 characters):

* Implement primary constructor
*  Update method

Addresses https://github.com/NuGet/NuGetGallery/issues/123

### CODE REVIEW

**Comment by joelverhagen** [comment]
Hello @KhanbalaRashidov. We generally don't take large, clean-up PRs like this. It adds churn to the codebase without an end-user scenario that is significantly benefited. I am not aware of how primary constructors or expression-bodied methods help with significantly with our maintainability also. Could you explain the reasoning behind this PR, in case I am misunderstanding?

More specifically, I don't think we as a team have adopted primary constructors in our codebase at all. Also, the size of the PR makes it hard to evaluate critically. Several steps mentioned in our https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md are missing.

**Comment by KhanbalaRashidov** [comment]
> Hello @KhanbalaRashidov. We generally don't take large, clean-up PRs like this. It adds churn to the codebase without an end-user scenario that is significantly benefited. I am not aware of how primary constructors or expression-bodied methods help with significantly with our maintainability also. Could you explain the reasoning behind this PR, in case I am misunderstanding?
> 
> More specifically, I don't think we as a team have adopted primary constructors in our codebase at all. Also, the size of the PR makes it hard to evaluate critically. Several steps mentioned in our https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md are missing.

Primary constructors are considered an “Everyday C#” developer feature. They allow you to define a class or struct along with its constructor in a single concise declaration. This can help you reduce the amount of boilerplate code you need to write.

**Comment by KhanbalaRashidov** [comment]
> Hello @KhanbalaRashidov. We generally don't take large, clean-up PRs like this. It adds churn to the codebase without an end-user scenario that is significantly benefited. I am not aware of how primary constructors or expression-bodied methods help with significantly with our maintainability also. Could you explain the reasoning behind this PR, in case I am misunderstanding?
> 
> More specifically, I don't think we as a team have adopted primary constructors in our codebase at all. Also, the size of the PR makes it hard to evaluate critically. Several steps mentioned in our https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md are missing.

The reason for such a large amount of change was that I integrated all the codes into this so that the subsequent additions to the codes would be compatible with it.

**Comment by erdembayar** [comment]
> Hello @KhanbalaRashidov. We generally don't take large, clean-up PRs like this. It adds churn to the codebase without an end-user scenario that is significantly benefited. I am not aware of how primary constructors or expression-bodied methods help with significantly with our maintainability also. Could you explain the reasoning behind this PR, in case I am misunderstanding?
> 
> More specifically, I don't think we as a team have adopted primary constructors in our codebase at all. Also, the size of the PR makes it hard to evaluate critically. Several steps mentioned in our https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md are missing.

+1 this, large size makes hard to review.

**Comment by KhanbalaRashidov** [comment]
> > Hello @KhanbalaRashidov. We generally don't take large, clean-up PRs like this. It adds churn to the codebase without an end-user scenario that is significantly benefited. I am not aware of how primary constructors or expression-bodied methods help with significantly with our maintainability also. Could you explain the reasoning behind this PR, in case I am misunderstanding?
> > More specifically, I don't think we as a team have adopted primary constructors in our codebase at all. Also, the size of the PR makes it hard to evaluate critically. Several steps mentioned in our https://github.com/NuGet/NuGetGallery/blob/main/CONTRIBUTING.md are missing.
> 
> +1 this, large size makes hard to review.

okay

**Comment by joelverhagen** [comment]
@KhanbalaRashidov, if this code change is blocking you from fixing a bug or adding a new feature to Gallery, please let us know. If you are working on another contribution beyond code style like this, feel free to open an issue describing your plan, then we can agree on a path forward before you put a lot of effort in. Thanks.

**Comment by KhanbalaRashidov** [comment]
> @KhanbalaRashidov, if this code change is blocking you from fixing a bug or adding a new feature to Gallery, please let us know. If you are working on another contribution beyond code style like this, feel free to open an issue describing your plan, then we can agree on a path forward before you put a lot of effort in. Thanks.

No, it doesn't. It's better to just implement and use the new features of .net in my opinion.

**Pull request closed without merging**
