### PR TITLE
Added a download rate stat to the package view

### PR DESCRIPTION
**Pull request by richorama**
re issue #2924 

image

### CODE REVIEW

**Comment by maartenba** [comment]
A nit: can the label be "Average downloads per day" (and perhaps a tooltip as well saying "Average download count over XYZ days")

Also is this per version or per ID?

**Comment by richorama** [comment]
Yup, I'll change the label and add a tool tip.

The calculation is for the ID.

```
TotalDownloadCount / (DateTime.UtcNow - package.Created)
```

**Comment by maartenba** [comment]
+1

**Comment by richorama** [comment]
done!
image

**Comment by maartenba** [comment]
Thanks Rich! Would you mind squashing the commits?

**Comment by richorama** [comment]
squashed!

**Comment by maartenba** [comment]
Thanks @richorama! I merged it into `dev`- will go live with a future deployment.

**Pull request closed without merging**
