### PR TITLE
Fix formatting of Manage Packages page with long data

### PR DESCRIPTION
**Pull request by scottbommarito**
https://github.com/NuGet/NuGetGallery/issues/5632
https://github.com/NuGet/NuGetGallery/issues/5303

Basically
1) only display first two owners
2) abbreviate owners with names too long
3) abbreviate package ID
4) make package ID not wrap
5) abbreviate version even more

This guarantees it will fit within the bounds of the table.

I have highlighted these changes in the screenshot below:
image

### CODE REVIEW

**Comment by anangaur** [comment]
What if the first owner name itself is long? In my view there should be a cap on the length of owner name shown else show each name with ellipsis. For more than 2 owners it should not be ellipsis but remaining count.

E.g.
owner1, owner2 + 1

**Comment by scottbommarito** [comment]
@anangaur as requested:

Owner username too long:
image

Too many owners:
image

**Comment by anangaur** [comment]
Nice!

**Comment by scottbommarito** [comment]
@joelverhagen The fix looks great at `lg` and `xs` but unfortunately bad at the sizes in between (in all browsers). Not sure how to improve it more but it's definitely better than the previous iteration and I don't want to spend too much time on it.

**Pull request merged**
