### PR TITLE
Support MinClientVersion <= 4.1.0.0

### PR DESCRIPTION
**Pull request by maartenba**
Fixes https://github.com/NuGet/Home/issues/5156

### CODE REVIEW

**Comment by emgarten** [comment]
4.1.0 is out already
4.3.0 is available in the CLI preview builds

Why does the gallery limit this? Just to verify the package is sane?

**Comment by joelverhagen** [comment]
Perhaps we should make max exclusive and switch to `5.0.0--`. For just say the major part must be less than or equal to 4. This seems like an overly strict requirement.

**Comment by skofman1** [comment]
Moved the issue to NuGetGallery repo: https://github.com/NuGet/NuGetGallery/issues/3866

**Comment by maartenba** [comment]
> 4.1.0 is out already
> 4.3.0 is available in the CLI preview builds

Unfortunately, there is no 4.1 of any of the client libraries on NuGet.org?

**Comment by skofman1** [comment]
@maartenba , why do we need MinClient version check at all? What was the intent on having it as part of the package validation process? I'm trying to understand if we should have an additional issue to remove this validation all together.

**Pull request merged**
