### PR TITLE
[UI] Add new themes for Alert component

### PR DESCRIPTION
**Pull request by martinrrm**
Adding the new themes to the alert component, this PR only changes CSS files, actual usage of the component will be in future PR's. 

##### Danger
image

##### Warning
image

##### Success
image

##### Info
image

##### Danger
image

##### Warning
image

##### Success
image

##### Info
image

Addresses https://github.com/NuGet/NuGetGallery/issues/9862

### CODE REVIEW

**Review by drewgillies — APPROVED** [review]

**Review by advay26 — APPROVED** [review]

**Comment by Nirmal4G** [comment]
@martinrrm Warning should be yellow (bright or dim depending on the base theme) and not orange-ish! It'll be difficult to see at a glance. When I glanced at this page, I thought both colors were the same. And no, I do not have any issues with recognising colors.

**Comment by martinrrm** [comment]
@Nirmal4G Hi! Thanks for your feedback, right now we are trying to stick with Fluent UI color tokens, nevertheless I agree with you, specially in the Light Theme is hard to distinguish the difference. This is another option we can use.

Also, I loved your idea for the info to be Info color, let me double check that with the designers/team

This is a possible alternative for the colors.
image

**Comment by Nirmal4G** [comment]
How about this one for the warning? GitHub uses it.

| Dark Theme Warning Color | Light Theme Warning Color |
| --- | --- |
| GitHub Warning Color on Dark Theme | GitHub Warning Color on Light Theme |

**Comment by martinrrm** [comment]
@Nirmal4G Let me check with designers, I don't think we should be using colors from other products given that there is a well-documented color theme for the components we are using.

**Comment by Nirmal4G** [comment]
@martinrrm Yeah. That's just for visual reference. Adjust the color to match NuGet branding. It would not be far off, IMO.

**Pull request merged**
