### PR TITLE
Add NUKE tab for dotnet tools

### PR DESCRIPTION
**Pull request by matkoch**
This implements https://github.com/NuGet/Home/pull/10782

### CODE REVIEW

**Comment by matkoch** [comment]
@joelverhagen example was included in the original PR (https://github.com/NuGet/Home/pull/10782#issue-619784625):

https://user-images.githubusercontent.com/5005566/115483309-d1732600-a250-11eb-9e7e-c684e88a81e3.png

I'm not sure what exactly I should test there. I basically did simple pattern matching according to the existing tabs. Is there anything I have overlooked?

**Comment by joelverhagen** [comment]
Regarding testing, what I've done for past tabs is make a package locally with a very long package ID and version then push it to my local running NuGetGallery. Then, I open the package details page and resize the window to various widths to make sure the text wrapping looks okay for the command. For example, this package ID causes wrapping: https://www.nuget.org/packages/GovUk.Education.SearchAndCompare.Ui.Shared/0.5.4-dependabot-npm-and-yarn-src-webpack-4-34-0.34

Regarding the screenshot, it helps the devs and PMs on my team get an accurate preview of what the tab is going to look like prior to approving the PR. Could you update the screenshot to include the `--version` part by running the code locally and capturing a screenshot?

Another thing I noticed is the yellow "contact maintainers" banner is linking to more of a docs page than a "get help" or "support" page. For example, Cake and Paket have dedicate support pages so that users can more easily get help if they need it:
- Paket: https://fsprojects.github.io/Paket/contact.html
- Cake: https://cakebuild.net/community/getting-help

What do you think about getting a similar page for NUKE?

**Comment by matkoch** [comment]
image
image
image

**Comment by matkoch** [comment]
Regarding the link, I'd probably prefer either

- https://nuke.build or
- https://github.com/nuke-build/nuke/issues/new/choose or 
- https://github.com/nuke-build/nuke/issues/new?template=bug_report.yml right away.

**Comment by matkoch** [comment]
@joelverhagen I changed it to `nuke.build` now. I think this provides all the necessary links (docs, GitHub, Slack, Twitter), and also gives a good introduction for those noticing it for the first time.

**Comment by joelverhagen** [comment]
Thanks for the screenshots!

I think link # 2 is the best (https://github.com/nuke-build/nuke/issues/new/choose). This seems to have Slack and GitHub issues. @JonDouglas - thoughts on the best link for the "Please contact its maintainers for support." link in the screenshots above?

**Comment by matkoch** [comment]
@joelverhagen just to explain my reasoning here: I'd like to help people helping themselves. That's why my first suggestion was the docs page that explains how CLI tools are used, which is exactly the point of the command. In any case, I could add another link to the docs also for the "new issue" link.

**Comment by joelverhagen** [comment]
FYI I changed the base branch to `dev`. The diff looks fine so I don't _think_ you'll need to change anything. But GitHub has merge UI has surprised me before 😄.

The commit list above could be eliminated with by rebasing your commit onto `dev` branch
image

**Review by joelverhagen — APPROVED** [review]

**Comment by matkoch** [comment]
Thank you @joelverhagen !

**Comment by joelverhagen** [comment]
You're most welcome 😃. Thanks for pushing through the design and implementation!

**Comment by matkoch** [comment]
Next step I'd like to approach is https://github.com/NuGet/Home/issues/10833

Out of curiosity, how likely would it be for this to get implemented? I can help, but I'm not sure if it aligns with plans and architecture.

**Comment by joelverhagen** [comment]
@matkoch, given this change is on the client side, I'll leave the discussion on that issue. I think there may be a blocker on another bug so we'll have to untangle the requirements and blockers carefully!

**Pull request merged**
