### PR TITLE
Fix Link Screen Reading Issue On Upload Package Page And About Page

### PR DESCRIPTION
**Pull request by Goodyear2017**
Remove aria-label and alt from links for bug # 1979902
Bug link:
https://devdiv.visualstudio.com/DevDiv/_queries/edit/?tempQueryId=86f20051-1835-446b-b283-b35a28cb6618&id=1979902

### CODE REVIEW

**Comment by ryuyu** [comment]
Can we add links to the relevant bugs in the description for this, https://github.com/NuGet/NuGetGallery/pull/9901 and https://github.com/NuGet/NuGetGallery/pull/9900 ? Thanks!

**Comment by Goodyear2017** [comment]
@ryuyu  Just added the links to PRs, thanks!

**Review by ryuyu — APPROVED** [review]

**Comment by erdembayar** [comment]
Could you please include screenshot for that change if available?

**Comment by Goodyear2017** [comment]
@erdembayar The change is for the link "Best Practices". Because we put a aria-label inside the link, screen reader reads the aria-label content instead of "best practices", removing the aria-label solve the issue. 
image

**Review by erdembayar — APPROVED** [review]

**Pull request merged**
