### PR TITLE
Use 100% width for input controls on edit package page

### PR DESCRIPTION
**Pull request by robertmuehsig**
Based on the idea of the previous PR https://github.com/NuGet/NuGetGallery/pull/3389 I found a existing css class that is currently only used on the signin & register page: "form-field-full".

This PR consistens of 3 "small" changes:

* Reuse existing "form-field-full" class and extend the width 100% to
textareas.
* Ensure a readable height for textares (only for "form-field-full"
cases)
* Adjust validation message and hint text to the same width (98.5% because of some
paddings & compatibility with the signin/register page)

The result of this PR would look like this (with validation message):

image

It also works with IE11:

image

The change should only affect the edit-package-page. The css changes should only apply to form-field-full usage, which is currently only applied for the simple signin & register. 

The register/signin page should work and look like before:

image

### CODE REVIEW

**Comment by 304NotModified** [comment]
Great improvement!

**Comment by robertmuehsig** [comment]
He - is there anything I could do (e.g. more testing) so that you might accept this PR (or at least verify - step by step to "merge" ;) ) ?

**Comment by robertmuehsig** [comment]
Sure 👍

**Comment by skofman1** [comment]
@xavierdecoster , I'm ok with taking the PR, but please check all affected pages (including scoped API keys, which is somewhat complex in implementation, and might react differently). Also, tryout different browsers.
After merge, we should create an issue and track this on the board.

**Comment by robertmuehsig** [comment]
whao... that was not intended. It seems my Git voodoo is too low - I will close this and open another one.

**Comment by robertmuehsig** [comment]
Created a new PR https://github.com/NuGet/NuGetGallery/pull/3710 with a minor adjustment to make sure this is really safe.

**Pull request closed without merging**
