### PR TITLE
Update Fabric Core to 11.0.1

### PR DESCRIPTION
**Pull request by dannyjdev**
### Changes
- Updated version 7.3.0 to 11.0.1
- Removed SquaredShape icon since it's no longer needed.

Addresses: https://github.com/NuGet/Engineering/issues/4756

### CODE REVIEW

**Comment by joelverhagen** [comment]
What kind of testing did you do you make sure we didn't regress the look-n-feel? IIRC we use more than just the icons from fabric. Maybe some typography ones are used... Would it be worth visually inspecting all places that use an `ms-*` CSS class?

**Comment by dannyjdev** [comment]
> What kind of testing did you do you make sure we didn't regress the look-n-feel? IIRC we use more than just the icons from fabric. Maybe some typography ones are used... Would it be worth visually inspecting all places that use an `ms-*` CSS class?

I actually did that, inspected the icons and checked if something looked different. And no, everything I checked looked fine.

**Review by joelverhagen — APPROVED** [review]

**Comment by lyndaidaii** [comment]
Have we ever used this SquaredShape?

**Comment by dannyjdev** [comment]
> Have we ever used this SquaredShape?

Yes, I used it on the frameworks tab, it was the only place I add it.

**Pull request merged**
