### PR TITLE
removed unnecessary http headers (see http://stackoverflow.com/questi…

### PR DESCRIPTION
**Pull request by chipitsine**
…ons/3418557/how-to-remove-asp-net-mvc-default-http-headers)

### CODE REVIEW

**Comment by chipitsine** [comment]
I signed CLA at https://cla.dotnetfoundation.org/

**Comment by xavierdecoster** [comment]
Thanks @chipitsine !
Can you please sign this CLA instead (note the 2 in the URL)? https://cla2.dotnetfoundation.org/
Our DNF bot will automatically pick it up and tag this PR accordingly.

**Comment by chipitsine** [comment]
done

**Comment by chipitsine** [comment]
I did the wrong patch.
will reopen pull request soon

**Pull request closed without merging**
