### PR TITLE
Fix for static code analyzers

### PR DESCRIPTION
**Pull request by scottbommarito**
Some static code analyzers fail on named arguments in attributes. This PR removes all of them to fix the issue.

### CODE REVIEW

**Comment by shishirx34** [comment]
Can you add the named arguments as a comment in there?
```
/*MaximumLength*/ 64
```

That way its readable plus passes code analyzers?

**Comment by scottbommarito** [comment]
@shishirx34 Nice suggestion, I will do it.

**Comment by robertmuehsig** [comment]
This named argument as a comment thing seems very strange - is this a recommended approach inside MSFT? It will "break" (or show missleading stuff) on refactorings.

**Comment by scottbommarito** [comment]
@robertmuehsig That is true, and a good concern to have. I believe @shishirx34 took the convention from javascript, which does not have named arguments, and in which you do see `/*argName*/` fairly often. We're waiting to hear back from the teams working on the static code analyzers to see if we don't have to bother with this.

**Comment by shishirx34** [comment]
@robertmuehsig - I agree it could be misleading on refactorings, however, the static values are very hard to read without context and if there isn't any option to have named arguments, this is something I believe is better to have, given refactorings shouldn't be often, even if done at any point the context most likely remains the same.

**Comment by agr** [comment]
Shouldn't it be filed as a bug to whoever owns those static analyzers that fail?

**Comment by skofman1** [comment]
@scottbommarito , is this PR still relevant?

**Comment by scottbommarito** [comment]
I think we can close it--was having trouble running the static code analyzers initially but it seems to no longer be an issue.

**Comment by scottbommarito** [comment]
@agr we have reached out to the people in charge of the tooling.

**Pull request closed without merging**
