### PR TITLE
changed `dotnet new` example

### PR DESCRIPTION
**Pull request by vlada-shubina**
Starting .NET 7.0, `dotnet new --install` became `dotnet new install`.
https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new-install

Therefore changed syntax in example

### CODE REVIEW

**Comment by vlada-shubina** [comment]
@baronfel fyi

**Comment by joelverhagen** [comment]
Thanks for the contribution, @vlada-shubina!

I'm curious about the timing of this change, i.e. when should it go live on NuGet.org. Should it wait until a certain % of users move to .NET 7? Or do you think we should just go for it since .NET 7 is GA'd?

What is the behavior if you use the new syntax on the old CLI or the old syntax on the new CLI?

**Comment by vlada-shubina** [comment]
@joelverhagen 

new syntax doesn't work in previous versions
old syntax works in .NET 7 with warning:
```
>dotnet new --install Boxed.Templates  
Warning: use of 'dotnet new --install' is deprecated. Use 'dotnet new install' instead.
For more information, run:
   dotnet new install -h

The following template packages will be installed:
   Boxed.Templates
...
```
aka.ms/dotnet-new leads to https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-new which explains new syntax almost on top. @baronfel do you know the adoption of .NET 7?  when do you think we should go for the change?

**Comment by joelverhagen** [comment]
@vlada-shubina, thanks again for pushing this. I'll run the change through the CI and get the verification and deployment process rolling.

**Comment by joelverhagen** [comment]
FYI I changed the base branch to `dev` which is where we start during verification.

**Review by joelverhagen — APPROVED** [review]

**Comment by joelverhagen** [comment]
Merged to `dev`. We'll take this to PROD (www.nuget.org) soon. Thanks again, @vlada-shubina!

**Pull request merged**
