### PR TITLE
Remove cloud service project from gallery

### PR DESCRIPTION
**Pull request by scottbommarito**
(moving it into NuGetDeployment)

cc @xavierdecoster @maartenba @skofman1

### CODE REVIEW

**Comment by maartenba** [comment]
Looks good to me, will let @xavierdecoster sign off on this one

**Comment by xavierdecoster** [comment]
Can you find out whether the following file is still needed? https://github.com/NuGet/NuGetGallery/blob/remove-cloud-service/NuGet.Cloud.targets

Looks good to me otherwise. Please hold off on merging until the PR against NuGetDeployment has been accepted and our deployment pipeline updated (merging this PR is the last step of the migration of our cloud projects).

**Comment by scottbommarito** [comment]
@xavierdecoster I'm pretty sure that NuGet.Cloud.targets is only used by the cloud project. I can build the project locally without it with no issues, but the cloud service project complained when I didn't have it so I moved it there. I have removed the file but let me know if there's anything else that I should check to see if it's safe to remove in addition to building the project.

**Comment by skofman1** [comment]
LGTM

**Comment by shishirx34** [comment]
Looks good.

**Comment by ngbrown** [comment]
@scottbommarito Using `wget` in powershell isn't available in PowerShell 2.0, which is all that is required in the `Readme.md` instructions.

**Comment by scottbommarito** [comment]
@ngbrown Filed an issue for updating the `Readme.md` instructions for minimum PowerShell version.

**Pull request merged**
