### PR TITLE
move to 8.0.301 sdk

### PR DESCRIPTION
**Pull request by SimonCropp**
Tracking issue: https://github.com/NuGet/Engineering/issues/5505

### CODE REVIEW

**Comment by joelverhagen** [comment]
This seems reasonable, we just need to make sure our various CI and release pipelines are happy with this change. Thanks!

**Comment by joelverhagen** [comment]
Our release builds have some problem with this change. I think we would need to explicitly install .NET 8 to a special place, or something like that. It will take us some time to work out these changes (some of which may be closed source). Is this change blocking you?

**Comment by SimonCropp** [comment]
> I think we would need to explicitly install .NET 8 to a special place

if u move to using the [dotnet-install scripts](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script) it will respect your globa.json and install the correct version

> Is this change blocking you?

we .net 6 is 3 years old and i did not have it installed. imo it make sense to target the current stable, since there are security fixes and new features that are unlocked by using it

**Comment by SimonCropp** [comment]
@joelverhagen can we merge this?

**Comment by erdembayar** [comment]
> can we merge this?

Sorry, it's quite busy period. Just pushed changes to internal release pipeline. Let's see if it fixes the problem.

**Comment by erdembayar** [comment]
> > can we merge this?
> 
> Sorry, it's quite busy period. Just pushed changes to internal release pipeline. Let's see if it fixes the problem.

I created PR for internal release pipeline. We need to merge them same time, otherwise things would break.

**Review by erdembayar — APPROVED** [review]
Thank you for contribution.

**Pull request merged**
