### PR TITLE
Some Docs Updates

### PR DESCRIPTION
**Pull request by scottbommarito**
`Netsh` doesn't support SNI on versions of Windows before 8, so `Enable-LocalTestMe.ps1` will fail when run. Added a comment in the docs that this is the case.

Also removed the outdated "DON'T DELETE THE TOPIC BRANCH" guidance and replaced it with the opposite advice.

(Fixes https://github.com/NuGet/NuGetGallery/issues/3162)

### CODE REVIEW

**Comment by scottbommarito** [comment]
(The first change was approved at https://github.com/NuGet/NuGetGallery/pull/3164 but needed to be reopened on dev.)

**Comment by scottbommarito** [comment]
@maartenba @skofman1 @harikmenon @ryuyu @shishirx34

**Comment by shishirx34** [comment]
LGTM :shipit:

**Comment by maartenba** [comment]
:shipit:

**Pull request merged**
