### PR TITLE
[ReleasePrep][2020.07.14]FI of master into dev

### PR DESCRIPTION
**Pull request by ryuyu**

### CODE REVIEW

**Comment by zhhyu** [comment]
I don't think we need this PR, there are no changes here.

**Comment by ryuyu** [comment]
There is a change labelled [HOTFIX].
I'm guessing we need this unless this was already pulled into dev, or it is a change that for some reason is not needed in dev.

**Comment by joelverhagen** [comment]
There is no diff. This PR is not necessary. It's possible a squash happened before when it shouldn't have.

**Comment by ryuyu** [comment]
Works for me.

**Pull request closed without merging**
