### PR TITLE
use Count instead of Where+Count

### PR DESCRIPTION
**Pull request by SimonCropp**
Shorten Linq syntax by using just Count instead of Where+Count.

### CODE REVIEW

**Review by erdembayar — APPROVED** [review]

**Comment by erdembayar** [comment]
LGTM, it's technically just a cosmetic syntax change, shouldn't change actual behavior.

**Comment by SimonCropp** [comment]
> technically just a cosmetic syntax change

nope. this halves the number of linq evaluation. so has memory, cpu, assembly size, build time, and jit time improvements. Admittedly some of thee would be difficult to measure. but the memory + cpu would impact a fast path

**Comment by erdembayar** [comment]
> > technically just a cosmetic syntax change
> 
> nope. this halves the number of linq evaluation. so has memory, cpu, assembly size, build time, and jit time improvements. Admittedly some of thee would be difficult to measure. but the memory + cpu would impact a fast path

Thank you for the clarification. I haven't done any performance-related work recently, my memory is vague. Also, I noticed that performance numbers vary for tfm. Unfortunately, we're still using net472.

**Comment by SimonCropp** [comment]
> Unfortunately, we're still using net472.

it will still result in perf improvements on net472

**Pull request merged**
