### PR TITLE
Fix #6725

### LINKED ISSUE #6725: Visual Issue: Organization forms are smaller then other forms
I noticed that this form has much more spacing:

image

... then other forms, e.g.:

image

This leads to some "jumping" in the navigation:

gif

Also the org management page has some margins around the actual site, which is not present on the other pages:

image

Is this "by design" or a good candidate for "up for grabs"?

### PR DESCRIPTION
**Pull request by robertmuehsig**
Set column number from 10 to 12 and reenable this setting on uploadpackage/account/apikeys (constants were deleted in a previous commit)

### CODE REVIEW

**Comment by robertmuehsig** [comment]
Fix for: #6725

**Comment by chenriksson** [comment]
@robertmuehsig Thank you for the contribution! Can you retarget the PR against dev, since we only apply hotfixes to master?

**Comment by robertmuehsig** [comment]
FYI: I changed the base branch from master to dev.

**Comment by chenriksson** [comment]
Thanks, @robertmuehsig... verified and merged!

**Pull request merged**
