### PR TITLE
Add AppVeyor CI

### PR DESCRIPTION
**Pull request by 304NotModified**
There is probably already a build server (saw "teamcity" somewhere referenced?) 

But:

1. the build & test status is not clear / not public visible
1. there is no web hook for the PR (build and tests)

AppVeyor is a great CI which integrated nicely in GitHub, .Net and is easy to setup.

Example output: 
https://ci.appveyor.com/project/304NotModified/nugetgallery/build/1.0.6

910 passed tests (not sure if AppVeyor found them all)

Steps to-do after merge:

1. Sign in to AppVeyor (https://ci.appveyor.com)
1. Click button "new project"
1. GitHub / select repository, click "add"
1. Click button "new build"
1. Build
1. Add AppVeyor webhook (should be automatically added? But failed last time to me)
1. (optional) Add badge with build/test status :)

### CODE REVIEW

**Comment by maartenba** [comment]
TeamCity indeed, and we're currently not planning on changing that immediately. But if you run your own gallery by all means use a CI system of choice :)

**Comment by 304NotModified** [comment]
> TeamCity indeed, and we're currently not planning on changing that immediately.

It's not meant as an replacement :) 

I would advise to enable a AppVeyor integration (next to the TeamCity CI), because it gives the following benefits:

- In a PR it's clear if the submitted code compiles and won't break any unit tests
- The build and test status is clear en public visible
- It looks professional IMO ;)



> Any chance you can squash the three commits before we accept the PR?

I not sure what you mean. Do you prefer one (1) commit? Do I need to send a new PR?

**Comment by maartenba** [comment]
Exactly, make it look like one commit - here's some (random) link on how to do this: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by 304NotModified** [comment]
Yes I will do that :) 

But good to know, what's the real benefit of a squash?

**Comment by maartenba** [comment]
In the change log it would show the change as just one commit. If this was a massive refactoring a few commits wouldn't hut but three commits for just one file is a lot of noise in the commit log (albeit we're guilty of this ourselves every once in a while)

**Comment by 304NotModified** [comment]
Funny stuff, squash, but I failed. I have now 5 commits... I will create a new PR, that's far more easy

**Pull request closed without merging**
