### PR TITLE
Don't show "list/unlist" options for packages that failed validation

### LINKED ISSUE #5992: Don't show "list/unlist" options for packages that failed validation
Repro:
1. Upload a package that will fail validation
2. Click on "Delete package" on Package page. 

Expected: 
1. List/unlist option not available.

Actual: it's there

@rido-min @anangaur

### PR DESCRIPTION
**Pull request by xavierdecoster**
Fixes #5992

### CODE REVIEW

**Comment by loic-sharma** [comment]
Can you add a screenshot of what it looks like if the package failed validation? Also, does the backend prevent listing/unlisting of packages that have failed validation?

**Comment by xavierdecoster** [comment]
Screenshot

image

**Comment by xavierdecoster** [comment]
@loic-sharma added a test + fix in PackageService to ensure listing of packages that failed validation is no longer possible.

**Comment by skofman1** [comment]
@xavierdecoster , for completeness, we should block list/unlist operations in the API as well.

**Pull request merged**
