### PR TITLE
Update Semver2 package details message (add Rider)

### PR DESCRIPTION
**Pull request by AndreyAkinshin**

### CODE REVIEW

**Comment by anangaur** [comment]
Plan to have link to a doc page that lists all the supported clients for SemVer 2.0.0 pkgs. Not there yet. We have a documentation issue for the same: https://github.com/NuGet/docs.microsoft.com-nuget/issues/376

**Comment by maartenba** [comment]
Wondering if this is somethign that could go hand in hand with the new site design? E.g. saw [Paket has a PR open for the package details page](https://github.com/NuGet/NuGetGallery/pull/4437) so this could probably fit in nicely as well?

**Comment by isaacabraham** [comment]
@maartenba that PR has been rejected, sadly. I would also suggest that this PR (or a sibling) is expanded to include other clients, such as Paket.

**Comment by forki** [comment]
adding the "me too" https://github.com/NuGet/NuGetGallery/pull/4448

**Comment by 304NotModified** [comment]
What's the idea with this PR? Keep it open for 2 more years? ;)

**Comment by joelverhagen** [comment]
Hey folks, this SemVer 2.0.0 warning banner was removed a while back. From our data we found that over 95% of clients support SemVer 2.0.0 parsing and the SemVer 2.0.0 V2 and V3 protocols. This meant the warning banner was more noisy that helpful for the majority of users.

Context: https://github.com/NuGet/NuGetGallery/issues/7836
Client context: https://github.com/NuGet/Home/issues/5201
NuGet.org change: https://github.com/NuGet/NuGetGallery/pull/7837

Looks like JetBrains Rider is mentioned in the docs:
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning#semantic-versioning-200

Do you feel that a further change is necessary at this point?

Apologies on the extensive delay.

**Comment by maartenba** [comment]
That's probably sufficient, thanks Joel!

**Comment by AndreyAkinshin** [comment]
@joelverhagen thanks for the update!

**Pull request closed without merging**
