### PR TITLE
improved the #r directive instructions

### PR DESCRIPTION
**Pull request by filipw**
This is a follow up to https://github.com/NuGet/NuGetGallery/pull/8375

Since `#r` is not exclusive to F#, it is a bit inaccurate to use the current header for the instructions - it would make sense to use a more generic name for it. 
Therefore I propose to rename `F# Interactive` to `.NET Interactive` as it then correctly captures both C# and F#.

### CODE REVIEW

**Comment by cartermp** [comment]
Note that the tab is correct as-is too, since F# Interactive is orthogonal to .NET Interactive. The disjoint nature of package acquisition for C# in "interactive" scenarios when compared to F# likely makes it more challenging to represent.

**Comment by filipw** [comment]
> Note that the tab is correct as-is too, since F# Interactive is orthogonal to .NET Interactive.

I meant `.NET Interactive` as a general class of interactive tools for .NET, not specifically the product `.NET Interactive`. I have renamed it to `Script & Interactive` which better conveys the meaning.

This captures both F# and C# *if* this syntax is supported in a given runner, as the explanation underneath states.

**Comment by LadyNaggaga** [comment]
PM - .NET Interactive here.  @filipw recommend tab name Script & Interactive sounds like a fair description. I have chatted with @cartermp about this as well.  A note would need to be included along the lines of _#r directive can be used in F# Interactive,  C# scripting and .NET Interactive_  thoughts?

**Comment by jcjiang** [comment]
That makes sense to me. I agree that we should add the additional context and proceed with the PR.

**Comment by drewgillies** [comment]
Screenshot FYI
image

**Review by drewgillies — APPROVED** [review]
Thanks for your contribution, @filipw! Merging.

**Pull request merged**
